version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout

     # yocto
     - run: cd ./docker && docker build --no-cache --build-arg USER=$USER -t rubuschl/bytedevkit:123 .
     - run: cd ./docker && docker run --rm -ti --user=$USER:$USER --workdir=/home/$USER -v $PWD/output:/home/$USER/poky/build rubuschl/bytedevkit:123
